plugin.id=sample-demo-jpa-domain
plugin.class=net.xdob.sample.domain.SampleJpaDomainPlugin
plugin.provider=pf4boot
plugin.dependencies=
plugin.description=sample shared JPA domain provider
plugin.requires=
plugin.license=Apache-2.0
