plugin.id=sample-unrelated-service
plugin.class=net.xdob.sample.unrelated.UnrelatedServicePlugin
plugin.provider=pf4boot
plugin.dependencies=
plugin.description=sample unrelated service plugin without JPA dependency
plugin.requires=
plugin.license=Apache-2.0
