server:
  port: 7788
  servlet:
    context-path:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
      max-http-header-size: 102400
spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  flyway:
    enabled: false
  pf4boot:
    #prod=deployment
    #dev=development
    runtime-mode: dev
    enabled: true
    classes-directories:
      - "build/classes/java/main"
      - "build/resources/main"
    lib-directories:
      - "lib"
      - "build/inline"
    main:
      allow-bean-definition-overriding: true
    controller:
      base-path: /api/pf4boot/
  web:
    resources:
      static-locations: classpath:/webui/,classpath:/static/
logging:
  file:
    name: ./logs/pf4boot.log
  level:
    root: INFO