plugin.id=sample-workflow
plugin.class=net.xdob.sample.workflow.WorkflowPlugin
plugin.provider=pf4boot
plugin.dependencies=sample-demo-jpa-domain,sample-user-book-service
plugin.description=sample workflow orchestration plugin
plugin.requires=
plugin.license=Apache-2.0
