server:
  port: 7788
  servlet:
    context-path:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
      max-http-header-size: 102400
spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/webui/,classpath:/static/
  flyway:
    enabled: false
  pf4boot:
    #prod=deployment
    #dev=development
    runtime-mode: prod
    enabled: true
    classes-directories:
      - "build/classes/java/main"
      - "build/resources/main"
    lib-directories:
      - "lib"
      - "build/inline"
    main:
      allow-bean-definition-overriding: true
    controller:
      base-path: /api/pf4boot/
  datasource:
    url: jdbc:h2:file:~/h2/pf4boot_demo;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    platform: h2
    username: sa
    password: ysyhljt2020*
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    use_sql_comments: true
    format_sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2/console
      settings:
        trace: true
        web-allow-others: true
logging:
  file:
    name: ./logs/demo.log
  level:
    root: INFO
    org.springframework.web: trace