package net.xdob.pf4boot.jpa.reload;

/**
 * JPA domain 刷新稳定失败码。
 *
 * <p>失败码会出现在管理接口和验收报告中，不能直接暴露异常类名。</p>
 */
public enum JpaDomainReloadFailureCode {
  RELOAD_DISABLED,
  PLAN_ONLY_MODE,
  DOMAIN_NOT_FOUND,
  DOMAIN_NOT_READY,
  PROVIDER_NOT_RUNNING,
  INFERRED_CONSUMER_PRESENT,
  CONCURRENT_RELOAD,
  MULTI_DOMAIN_PROVIDER_UNSUPPORTED,
  LIFECYCLE_OPERATION_UNAVAILABLE,
  UNSUPPORTED_REPLACEMENT_PATH,
  INVALID_REQUEST,
  DRAIN_TIMEOUT,
  DRAIN_REJECTED,
  CONSUMER_STOP_FAILED,
  PROVIDER_STOP_FAILED,
  PROVIDER_START_FAILED,
  CONSUMER_START_FAILED,
  HEALTH_CHECK_FAILED,
  OPERATION_FAILED
}
