server:
  port: 6688
  servlet:
    context-path:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
      max-http-header-size: 102400
spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/webui/,classpath:/static/
  flyway:
    enabled: false
  pf4boot:
    runtime-mode: development
    enabled: true
    classes-directories:
      - "build/classes/java/main"
      - "build/resources/main"
    lib-directories:
      - "libs"
    main:
      allow-bean-definition-overriding: true
    controller:
      base-path: /api/pf4boot/
  datasource:
    url: jdbc:h2:file:~/h2/pf4boot_demo;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    platform: h2
    username: sa
    password: ysyhljt2020*
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
    h2:
      console:
        enabled: true
        path: /console
        settings:
          trace: false
          web-allow-others: false
logging:
  file: ./logs/demo.log
  level:
    root: INFO