server:
  port: 7788
  servlet:
    context-path:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
      max-http-header-size: 102400
spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  flyway:
    enabled: false
  pf4boot:
    runtime-mode: development
    enabled: true
    classes-directories:
      - "build/classes/java/main"
      - "build/resources/main"
    lib-directories:
      - "lib"
      - "build/inline"
    main:
      allow-bean-definition-overriding: true
    controller:
      base-path: /api/pf4boot/
  datasource:
    url: jdbc:h2:file:~/h2/pf4boot_demo;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;NON_KEYWORDS=user
    username: sa
    password: ysyhljt2020*
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    use_sql_comments: true
    format_sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2/console
      settings:
        trace: true
        web-allow-others: true
  sql:
    init:
      platform: h2
  web:
    resources:
      static-locations: classpath:/webui/,classpath:/static/
logging:
  config: ./config/logback-spring.xml